### ISSUE TITLE
Bad Request error

### ISSUE THREAD

**Issue by volodymyrdovhan** [eadtech-moodle/moodle-mod_cloudstudio#10]
Hello,

I got an error when tried to test the Cloud Studio.
![image](https://github.com/user-attachments/assets/dab88157-6616-4b84-aff3-b7e5fe0854a0)

**Comment by eduardokraus** [comment]
https://eadtech.cloudstudio.com.br/ not https://admin.cloudstudio.com.br/

**Comment by volodymyrdovhan** [comment]
![image](https://github.com/user-attachments/assets/20924493-9770-4148-965f-6b73647ee6a1)

![image](https://github.com/user-attachments/assets/12278307-1dd9-4651-9bf7-9b11abc52094)

**Comment by eduardokraus** [comment]
I was unable to reproduce this error in any Moodle instance with the plugin in production.

**Comment by volodymyrdovhan** [comment]
Theoretically, it can happen in the local env. I suppose we can close this issue, if any user gets this error - will report a new issue.
